development:
  secret_key_base: c6e488703ae1bdd4f7814506b6e4a3e6092d690b46c7a026a0564767cc41d1505e4e8f45dc7d6b9491155e58c0940b1c56debf4bb9b7256af0be7e21cc657688
  AWS_ACCESS_KEY_ID: AKIAJWGEEA5N7XRO7FYQ
  AWS_SECRET_ACCESS_KEY: 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
  S3_BUCKET_NAME: wannawatch.bucket


test:
  secret_key_base: 399efe412031c395c318af5ba07e7a627fb20a2a04795b9e8f2d41e17092548e57c990de4813756b8be85970294176bdaf9fecec208a1fff72ad3fc24e930f4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  AWS_ACCESS_KEY_ID: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  AWS_SECRET_ACCESS_KEY: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  S3_BUCKET_NAME: <%= ENV["S3_BUCKET_NAME"] %>
